//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionWeb.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Detalle_Factura
    {
        public int ID { get; set; }
        public int ID_Fac { get; set; }
        public int ID_Pro { get; set; }
        public decimal Precio { get; set; }
        public decimal Cant { get; set; }
        public decimal SubTotal { get; set; }
        public int Estado { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Factura Factura { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Producto Producto { get; set; }
    }
}
