//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionWeb.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Producto
    {
        public Producto()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public decimal Stock { get; set; }
        public int Estado { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
    }
}
