//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Menu
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public int ID_Menu { get; set; }
        public int Estado { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
